# Custom Headers must be nested inside a top-level customHeaders key
Resources:
  MyAmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: nlw-frontend
      CustomHeaders:
        - Key: Access-Control-Allow-Origin
          Value: 'https://main.d3dn7d96quisvt.amplifyapp.com'
        - Key: Access-Control-Allow-Methods
          Value: 'GET, POST, OPTIONS'
        - Key: Access-Control-Allow-Headers
          Value: '*'